### ISSUE TITLE
Q: Testnet availability?

### ISSUE THREAD

**Issue by dantrevino** [tokensoft/tokensoft_token_stacks#2]
Do you have a token deployed to testnet that I can test Boom wallet with?

**Comment by pooleja** [comment]
I will post here once we get it on testnet.

**Comment by pooleja** [comment]
Hi @dantrevino here is the address it is deployed at.  Just let me know an address and I can send some tokens for testing.

ST2SD3QC9R3XJCY88ZTERP4APZEH49HJQREKT5MZ9.tokensoft-token

**Comment by dantrevino** [comment]
Thanks.  STQTK2AMC92ZN0ZWTMB6N53E4QF6CNH98QZTF8BN

**Comment by pooleja** [comment]
https://explorer.stacks.co/txid/0x2f848c1962ed0304d459971f27b04cb94e9bbb0c9a5c68d71fd2f3e19817c7c4?chain=testnet

**Comment by pooleja** [comment]
Closing issue.
