### ISSUE TITLE
Remove initialize function

### ISSUE THREAD

**Issue by friedger** [tokensoft/tokensoft_token_stacks#3]
Initialize should be done on deployment, the relevant variables should be constants.

**Comment by pooleja** [comment]
We have automated contract deployment tools that need to have a locked down contract code so that we can deploy and initialize with runtime vars.  If this wasn't the case, I would def just put it into the contract.  Closing for now.

**Comment by friedger** [comment]
I usually do a search and replace of the contract code before deployment.
